//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_LIII_Dejan_Prodanovic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployee
    {
        public int EmployeeID { get; set; }
        public string HotelFloor { get; set; }
        public string Citizenship { get; set; }
        public string Gender { get; set; }
        public string Engagement { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Mail { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Username { get; set; }
    }
}
